name: Update Metrics

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0,3,6,9,12,15,18,21 * * *'

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          output_action: commit
          committer_branch: main
          filename: metrics.svg
          config_timezone: Asia/Nanjing
          # Options
          user: KrisLiu16
          template: classic
          # Base content
          base: header, activity, community
          base_indepth: yes
          # Isocalendar
          plugin_isocalendar: no
          # Introduction
          plugin_introduction: yes
          plugin_introduction_title: no
          # Repositories
          plugin_repositories: yes
          plugin_repositories_featured: KrisLiu16/OnlineJudge-GOJ, criyle/go-judge
          # Languages
          plugin_languages: no
          plugin_languages_ignored: html, css
          plugin_languages_skipped: RSSHub, Placeholder, Tai-e, tai-e-ipta, WALA-Sharp, TOPLAS19-Reproduction, XCPC, Raft, yjl9903.github.io, NJUST-XCPC-WinterTraining-Solutions, OI-Public-Library, XLor-HDu, XLor-PKu, XLor-UVa, NJUST-CPany
          plugin_languages_details: bytes-size, percentage
          # Wakatime
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_days: 7
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, editors-graphs, os, os-graphs
          plugin_wakatime_limit: 3
